config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)

    redirect_to articles_path
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <p><%= f.label :title %></p>
  <%= f.text_field :title, style: "width: 350px;" %>

  <p><%= f.label :content %></p>
  <%= f.text_area :content, :rows => 10, style: "width: 100%" %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
        <% @articles.each do |article| %>
          <div class="article">
            <h2><%= link_to article.title, article_path(article), class: "headline" %></h2>
            <div class="flexbox">
              <p><%= article.content %></p>
              <%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure?"  } do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="article">
        <h2>Create article</h2>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="article">
        <h2 class="headline"><%= @article.title %></h2>
        <p><%= @article.content %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

  </head>

  <body>
    <div class="navbar">
      <h1>NAVBAR</h1>
      <div class="button-wrapper">
        <%= link_to 'Create new article', new_article_path, class: "add-button" %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>